# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #sync_code_signing(type: "appstore") 
    #match(type: 'appstore', readonly: true)

    
    #create_keychain(
    #  name: ENV["MATCH_KEYCHAIN_NAME"],
    #  password: ENV["MATCH_PASSWORD"],
    #  default_keychain: true,
    #  unlock: true,
    #  timeout: 3600,
    #  add_to_search_list: true
    #)

    #match(
    #  type: "appstore",
    #  keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
    #  keychain_password: ENV["MATCH_PASSWORD"],
    #  readonly: true
    #)


    get_certificates
    get_provisioning_profile
    #build_app
    build_app(export_xcargs: "-allowProvisioningUpdates")

    upload_to_testflight
  end
end
